name: Unit tests
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    env:
      CALLING_FROM_GITHUB: yes
    container: node:10.18-jessie
    defaults:
      run:
        working-directory: ./data_writer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Spago install
        run: npx spago install
      - name: Spago build
        run: npx spago build
      - name: Spago test
        run: npx spago test
